// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/transaction/transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	PricePerUnit         float32  `protobuf:"fixed32,4,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Product) GetPricePerUnit() float32 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Beneficiary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Beneficiary) Reset()         { *m = Beneficiary{} }
func (m *Beneficiary) String() string { return proto.CompactTextString(m) }
func (*Beneficiary) ProtoMessage()    {}
func (*Beneficiary) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{1}
}

func (m *Beneficiary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Beneficiary.Unmarshal(m, b)
}
func (m *Beneficiary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Beneficiary.Marshal(b, m, deterministic)
}
func (m *Beneficiary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Beneficiary.Merge(m, src)
}
func (m *Beneficiary) XXX_Size() int {
	return xxx_messageInfo_Beneficiary.Size(m)
}
func (m *Beneficiary) XXX_DiscardUnknown() {
	xxx_messageInfo_Beneficiary.DiscardUnknown(m)
}

var xxx_messageInfo_Beneficiary proto.InternalMessageInfo

func (m *Beneficiary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Transaction struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Merchantid           string               `protobuf:"bytes,2,opt,name=merchantid,proto3" json:"merchantid,omitempty"`
	Beneficiary          *Beneficiary         `protobuf:"bytes,3,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Products             []*Product           `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetMerchantid() string {
	if m != nil {
		return m.Merchantid
	}
	return ""
}

func (m *Transaction) GetBeneficiary() *Beneficiary {
	if m != nil {
		return m.Beneficiary
	}
	return nil
}

func (m *Transaction) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Transaction) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "transaction.Product")
	proto.RegisterType((*Beneficiary)(nil), "transaction.Beneficiary")
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
}

func init() { proto.RegisterFile("rpc/transaction/transaction.proto", fileDescriptor_8382c0c9a5d78224) }

var fileDescriptor_8382c0c9a5d78224 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x0d, 0xe5, 0x43, 0x99, 0xa2, 0x87, 0x0d, 0x87, 0x86, 0x44, 0xc5, 0x9e, 0xb8, 0xd0, 0x2a,
	0x9c, 0xf4, 0x62, 0xe4, 0x6e, 0x42, 0x1a, 0xbc, 0x78, 0x21, 0xdb, 0xed, 0x52, 0x26, 0x61, 0xbb,
	0x9b, 0xed, 0xd6, 0x84, 0xf8, 0x83, 0xfc, 0x9b, 0xa6, 0xdb, 0x22, 0x05, 0x0f, 0xde, 0x66, 0xde,
	0xbc, 0x37, 0xfb, 0xe6, 0x65, 0xe1, 0x5e, 0x2b, 0x16, 0x1a, 0x4d, 0xb3, 0x9c, 0x32, 0x83, 0x32,
	0x6b, 0xd6, 0x81, 0xd2, 0xd2, 0x48, 0xe2, 0x36, 0xa0, 0xd1, 0x5d, 0x2a, 0x65, 0xba, 0xe3, 0xa1,
	0x1d, 0xc5, 0xc5, 0x26, 0x34, 0x28, 0x78, 0x6e, 0xa8, 0x50, 0x15, 0xdb, 0xff, 0x82, 0x8b, 0xa5,
	0x96, 0x49, 0xc1, 0x0c, 0xb9, 0x06, 0x07, 0x13, 0xaf, 0x35, 0x6e, 0x4d, 0xfa, 0x91, 0x83, 0x09,
	0x21, 0xd0, 0xc9, 0xa8, 0xe0, 0x9e, 0x63, 0x11, 0x5b, 0x97, 0x58, 0x91, 0xa1, 0xf1, 0xda, 0x15,
	0x56, 0xd6, 0xc4, 0x87, 0x81, 0xd2, 0xc8, 0xf8, 0x92, 0xeb, 0xf7, 0x72, 0xd6, 0x19, 0xb7, 0x26,
	0x4e, 0x74, 0x82, 0x91, 0x21, 0x74, 0x6d, 0xef, 0x75, 0xed, 0xb0, 0x6a, 0xfc, 0x1b, 0x70, 0x17,
	0x3c, 0xe3, 0x1b, 0x64, 0x48, 0xf5, 0xfe, 0xdc, 0x80, 0xff, 0xed, 0x80, 0xbb, 0x3a, 0x1e, 0xf3,
	0xc7, 0xe0, 0x2d, 0x80, 0xe0, 0x9a, 0x6d, 0x69, 0x66, 0x30, 0xa9, 0x6d, 0x36, 0x10, 0xf2, 0x0c,
	0x6e, 0x7c, 0x5c, 0x6f, 0x3d, 0xbb, 0x33, 0x2f, 0x68, 0x46, 0xd6, 0x78, 0x3e, 0x6a, 0x92, 0xc9,
	0x03, 0x5c, 0xaa, 0x2a, 0x97, 0xdc, 0xeb, 0x8c, 0xdb, 0x13, 0x77, 0x36, 0x3c, 0x11, 0xd6, 0xa1,
	0x45, 0xbf, 0x2c, 0xf2, 0x04, 0xc0, 0x34, 0xa7, 0x86, 0x27, 0x6b, 0x6a, 0xec, 0x9d, 0xee, 0x6c,
	0x14, 0x54, 0xf9, 0x07, 0x87, 0xfc, 0x83, 0xd5, 0x21, 0xff, 0xa8, 0x5f, 0xb3, 0x5f, 0x0d, 0x79,
	0x81, 0xab, 0x1d, 0xcd, 0xcd, 0x5a, 0xc8, 0x04, 0x37, 0xc8, 0x13, 0xaf, 0xf7, 0xaf, 0x7a, 0x50,
	0x0a, 0xde, 0x6a, 0xfe, 0x62, 0xfe, 0xf1, 0x98, 0xa2, 0xd9, 0x16, 0x71, 0xc0, 0xa4, 0x08, 0x75,
	0x21, 0x72, 0x4d, 0x05, 0x86, 0x29, 0x7e, 0xee, 0xf6, 0x53, 0xad, 0xd8, 0x94, 0x2a, 0x0c, 0xcf,
	0xbe, 0x4e, 0xdc, 0xb3, 0x6b, 0xe7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xd8, 0x72, 0x7a,
	0x54, 0x02, 0x00, 0x00,
}
