// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/transaction/transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Productuid           string   `protobuf:"bytes,1,opt,name=productuid,proto3" json:"productuid,omitempty"`
	Productname          string   `protobuf:"bytes,2,opt,name=productname,proto3" json:"productname,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	PricePerUnit         float32  `protobuf:"fixed32,4,opt,name=pricePerUnit,proto3" json:"pricePerUnit,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductuid() string {
	if m != nil {
		return m.Productuid
	}
	return ""
}

func (m *Product) GetProductname() string {
	if m != nil {
		return m.Productname
	}
	return ""
}

func (m *Product) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Product) GetPricePerUnit() float32 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Transaction struct {
	Transactionuid       string               `protobuf:"bytes,1,opt,name=transactionuid,proto3" json:"transactionuid,omitempty"`
	Merchantuid          string               `protobuf:"bytes,2,opt,name=merchantuid,proto3" json:"merchantuid,omitempty"`
	Beneficiaryuid       string               `protobuf:"bytes,3,opt,name=beneficiaryuid,proto3" json:"beneficiaryuid,omitempty"`
	Reviewed             bool                 `protobuf:"varint,4,opt,name=reviewed,proto3" json:"reviewed,omitempty"`
	Submitted            bool                 `protobuf:"varint,5,opt,name=submitted,proto3" json:"submitted,omitempty"`
	Products             []*Product           `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReviewedAt           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	SubmittedAt          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTransactionuid() string {
	if m != nil {
		return m.Transactionuid
	}
	return ""
}

func (m *Transaction) GetMerchantuid() string {
	if m != nil {
		return m.Merchantuid
	}
	return ""
}

func (m *Transaction) GetBeneficiaryuid() string {
	if m != nil {
		return m.Beneficiaryuid
	}
	return ""
}

func (m *Transaction) GetReviewed() bool {
	if m != nil {
		return m.Reviewed
	}
	return false
}

func (m *Transaction) GetSubmitted() bool {
	if m != nil {
		return m.Submitted
	}
	return false
}

func (m *Transaction) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Transaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Transaction) GetReviewedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ReviewedAt
	}
	return nil
}

func (m *Transaction) GetSubmittedAt() *timestamp.Timestamp {
	if m != nil {
		return m.SubmittedAt
	}
	return nil
}

type GetProductListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductListRequest) Reset()         { *m = GetProductListRequest{} }
func (m *GetProductListRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductListRequest) ProtoMessage()    {}
func (*GetProductListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{2}
}

func (m *GetProductListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductListRequest.Unmarshal(m, b)
}
func (m *GetProductListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductListRequest.Marshal(b, m, deterministic)
}
func (m *GetProductListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductListRequest.Merge(m, src)
}
func (m *GetProductListRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductListRequest.Size(m)
}
func (m *GetProductListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductListRequest proto.InternalMessageInfo

type ProductList struct {
	ProductList          []*Product `protobuf:"bytes,1,rep,name=productList,proto3" json:"productList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductList) Reset()         { *m = ProductList{} }
func (m *ProductList) String() string { return proto.CompactTextString(m) }
func (*ProductList) ProtoMessage()    {}
func (*ProductList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{3}
}

func (m *ProductList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductList.Unmarshal(m, b)
}
func (m *ProductList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductList.Marshal(b, m, deterministic)
}
func (m *ProductList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductList.Merge(m, src)
}
func (m *ProductList) XXX_Size() int {
	return xxx_messageInfo_ProductList.Size(m)
}
func (m *ProductList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductList.DiscardUnknown(m)
}

var xxx_messageInfo_ProductList proto.InternalMessageInfo

func (m *ProductList) GetProductList() []*Product {
	if m != nil {
		return m.ProductList
	}
	return nil
}

type ReviewTransactionRequest struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReviewTransactionRequest) Reset()         { *m = ReviewTransactionRequest{} }
func (m *ReviewTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*ReviewTransactionRequest) ProtoMessage()    {}
func (*ReviewTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{4}
}

func (m *ReviewTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewTransactionRequest.Unmarshal(m, b)
}
func (m *ReviewTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewTransactionRequest.Marshal(b, m, deterministic)
}
func (m *ReviewTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewTransactionRequest.Merge(m, src)
}
func (m *ReviewTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_ReviewTransactionRequest.Size(m)
}
func (m *ReviewTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewTransactionRequest proto.InternalMessageInfo

func (m *ReviewTransactionRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type SubmitTransactionRequest struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubmitTransactionRequest) Reset()         { *m = SubmitTransactionRequest{} }
func (m *SubmitTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionRequest) ProtoMessage()    {}
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8382c0c9a5d78224, []int{5}
}

func (m *SubmitTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionRequest.Unmarshal(m, b)
}
func (m *SubmitTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionRequest.Merge(m, src)
}
func (m *SubmitTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionRequest.Size(m)
}
func (m *SubmitTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionRequest proto.InternalMessageInfo

func (m *SubmitTransactionRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "transaction.Product")
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*GetProductListRequest)(nil), "transaction.GetProductListRequest")
	proto.RegisterType((*ProductList)(nil), "transaction.ProductList")
	proto.RegisterType((*ReviewTransactionRequest)(nil), "transaction.ReviewTransactionRequest")
	proto.RegisterType((*SubmitTransactionRequest)(nil), "transaction.SubmitTransactionRequest")
}

func init() { proto.RegisterFile("rpc/transaction/transaction.proto", fileDescriptor_8382c0c9a5d78224) }

var fileDescriptor_8382c0c9a5d78224 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0x3f, 0x92, 0x71, 0x55, 0x89, 0x51, 0x11, 0xab, 0x08, 0x41, 0xb0, 0x04, 0xca,
	0xa5, 0x36, 0xa4, 0x12, 0x12, 0x20, 0x0e, 0x41, 0x42, 0x5c, 0x38, 0x44, 0x6e, 0xe9, 0x81, 0x0b,
	0x5a, 0xaf, 0xa7, 0xe9, 0x4a, 0xf5, 0x07, 0xeb, 0x75, 0x50, 0xff, 0x08, 0x12, 0x57, 0x7e, 0x29,
	0xf2, 0xda, 0x71, 0xd6, 0x69, 0xd3, 0x5e, 0x7a, 0xdb, 0x79, 0xf3, 0x66, 0xfc, 0xe6, 0xcd, 0xc8,
	0xf0, 0x52, 0xe5, 0x22, 0xd0, 0x8a, 0xa7, 0x05, 0x17, 0x5a, 0x66, 0xa9, 0xfd, 0xf6, 0x73, 0x95,
	0xe9, 0x0c, 0x5d, 0x0b, 0x1a, 0xbd, 0x58, 0x64, 0xd9, 0xe2, 0x8a, 0x02, 0x93, 0x8a, 0xca, 0x8b,
	0x40, 0xcb, 0x84, 0x0a, 0xcd, 0x93, 0xbc, 0x66, 0x7b, 0x7f, 0x1d, 0xd8, 0x9f, 0xab, 0x2c, 0x2e,
	0x85, 0xc6, 0xe7, 0x00, 0x79, 0xfd, 0x2c, 0x65, 0xcc, 0x9c, 0xb1, 0x33, 0x19, 0x86, 0x16, 0x82,
	0x63, 0x70, 0x9b, 0x28, 0xe5, 0x09, 0xb1, 0x9e, 0x21, 0xd8, 0x10, 0x22, 0xec, 0x94, 0xa9, 0xd4,
	0xac, 0x6f, 0x52, 0xe6, 0x8d, 0x1e, 0x1c, 0xe4, 0x4a, 0x0a, 0x9a, 0x93, 0xfa, 0x5e, 0xe5, 0x76,
	0xc6, 0xce, 0xa4, 0x17, 0x76, 0x30, 0x3c, 0x82, 0x5d, 0x13, 0xb3, 0x5d, 0x93, 0xac, 0x03, 0xef,
	0x5f, 0x1f, 0xdc, 0xb3, 0xf5, 0x30, 0xf8, 0x1a, 0x0e, 0xad, 0xd9, 0xd6, 0x1a, 0x37, 0xd0, 0x4a,
	0x67, 0x42, 0x4a, 0x5c, 0xf2, 0xd4, 0x0c, 0xd2, 0xe8, 0xb4, 0xa0, 0xaa, 0x53, 0x44, 0x29, 0x5d,
	0x48, 0x21, 0xb9, 0xba, 0xae, 0x48, 0xb5, 0xe2, 0x0d, 0x14, 0x47, 0x30, 0x50, 0xb4, 0x94, 0xf4,
	0x9b, 0x62, 0xa3, 0x7b, 0x10, 0xb6, 0x31, 0x3e, 0x83, 0x61, 0x51, 0x46, 0x89, 0xd4, 0x9a, 0x62,
	0xa3, 0x7b, 0x10, 0xae, 0x01, 0x7c, 0x03, 0x83, 0xc6, 0x98, 0x82, 0xed, 0x8d, 0xfb, 0x13, 0x77,
	0x7a, 0xe4, 0xdb, 0xbb, 0x6a, 0x3c, 0x0f, 0x5b, 0x16, 0xbe, 0x07, 0x10, 0x8a, 0xb8, 0xa6, 0xf8,
	0x27, 0xd7, 0x6c, 0x7f, 0xec, 0x4c, 0xdc, 0xe9, 0xc8, 0xaf, 0xf7, 0xe7, 0xaf, 0xf6, 0xe7, 0x9f,
	0xad, 0xf6, 0x17, 0x0e, 0x1b, 0xf6, 0x4c, 0xe3, 0x47, 0x70, 0x57, 0xb2, 0xaa, 0xda, 0xc1, 0xbd,
	0xb5, 0xb0, 0xa2, 0xcf, 0x34, 0x7e, 0x82, 0x83, 0x56, 0x76, 0x55, 0x3d, 0xbc, 0xb7, 0xda, 0x6d,
	0xf9, 0x33, 0xed, 0x3d, 0x85, 0x27, 0x5f, 0x49, 0x37, 0xe3, 0x7c, 0x93, 0x85, 0x0e, 0xe9, 0x57,
	0x49, 0x85, 0xf6, 0xbe, 0x80, 0x6b, 0xa1, 0xf8, 0xae, 0x3d, 0x9e, 0x2a, 0x64, 0xce, 0x1d, 0x9e,
	0xd8, 0x44, 0xef, 0x1c, 0x58, 0x68, 0xc4, 0x5a, 0x97, 0xd0, 0x7c, 0x02, 0x3f, 0x80, 0x7d, 0xec,
	0xe6, 0x1a, 0xdc, 0x29, 0xeb, 0xf4, 0xb4, 0xab, 0x6c, 0x72, 0xd5, 0xf7, 0xd4, 0x8c, 0xf1, 0xb0,
	0x7d, 0xa7, 0x7f, 0x7a, 0x80, 0x56, 0xf2, 0x94, 0xd4, 0x52, 0x0a, 0xc2, 0x39, 0x1c, 0x76, 0x6d,
	0x42, 0xaf, 0xd3, 0xef, 0x56, 0x0f, 0x47, 0xec, 0x36, 0x7f, 0x8c, 0x2d, 0x8f, 0xf0, 0x1c, 0x1e,
	0xdf, 0x30, 0x06, 0x5f, 0x75, 0x0a, 0xb6, 0x19, 0x37, 0xda, 0x3a, 0x4b, 0xdd, 0xf7, 0x86, 0x31,
	0x1b, 0x7d, 0xb7, 0x19, 0x77, 0x57, 0xdf, 0xcf, 0x27, 0x3f, 0xde, 0x2e, 0xa4, 0xbe, 0x2c, 0x23,
	0x5f, 0x64, 0x49, 0xa0, 0xca, 0xa4, 0x50, 0x3c, 0x91, 0xc1, 0x42, 0x2e, 0xaf, 0xae, 0x8f, 0x55,
	0x2e, 0x8e, 0x79, 0x2e, 0x83, 0x8d, 0xdf, 0x5b, 0xb4, 0x67, 0xce, 0xef, 0xe4, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0xa4, 0x82, 0xf3, 0xf8, 0x04, 0x00, 0x00,
}
