// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/merchant/merchant.proto

package merchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Merchant struct {
	Merchantuid          string               `protobuf:"bytes,1,opt,name=merchantuid,proto3" json:"merchantuid,omitempty"`
	Storeemail           string               `protobuf:"bytes,2,opt,name=storeemail,proto3" json:"storeemail,omitempty"`
	Storename            string               `protobuf:"bytes,3,opt,name=storename,proto3" json:"storename,omitempty"`
	Wallet               string               `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{0}
}

func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchant.Unmarshal(m, b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return xxx_messageInfo_Merchant.Size(m)
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetMerchantuid() string {
	if m != nil {
		return m.Merchantuid
	}
	return ""
}

func (m *Merchant) GetStoreemail() string {
	if m != nil {
		return m.Storeemail
	}
	return ""
}

func (m *Merchant) GetStorename() string {
	if m != nil {
		return m.Storename
	}
	return ""
}

func (m *Merchant) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *Merchant) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Merchant) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type CreateMerchantRequest struct {
	Storeemail           string   `protobuf:"bytes,1,opt,name=storeemail,proto3" json:"storeemail,omitempty"`
	Storename            string   `protobuf:"bytes,2,opt,name=storename,proto3" json:"storename,omitempty"`
	Wallet               string   `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMerchantRequest) Reset()         { *m = CreateMerchantRequest{} }
func (m *CreateMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMerchantRequest) ProtoMessage()    {}
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{1}
}

func (m *CreateMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMerchantRequest.Unmarshal(m, b)
}
func (m *CreateMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMerchantRequest.Marshal(b, m, deterministic)
}
func (m *CreateMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMerchantRequest.Merge(m, src)
}
func (m *CreateMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMerchantRequest.Size(m)
}
func (m *CreateMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMerchantRequest proto.InternalMessageInfo

func (m *CreateMerchantRequest) GetStoreemail() string {
	if m != nil {
		return m.Storeemail
	}
	return ""
}

func (m *CreateMerchantRequest) GetStorename() string {
	if m != nil {
		return m.Storename
	}
	return ""
}

func (m *CreateMerchantRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type UpdateMerchantRequest struct {
	Merchantuid          string   `protobuf:"bytes,1,opt,name=merchantuid,proto3" json:"merchantuid,omitempty"`
	Storeemail           string   `protobuf:"bytes,2,opt,name=storeemail,proto3" json:"storeemail,omitempty"`
	Storename            string   `protobuf:"bytes,3,opt,name=storename,proto3" json:"storename,omitempty"`
	Wallet               string   `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMerchantRequest) Reset()         { *m = UpdateMerchantRequest{} }
func (m *UpdateMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMerchantRequest) ProtoMessage()    {}
func (*UpdateMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{2}
}

func (m *UpdateMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMerchantRequest.Unmarshal(m, b)
}
func (m *UpdateMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMerchantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMerchantRequest.Merge(m, src)
}
func (m *UpdateMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMerchantRequest.Size(m)
}
func (m *UpdateMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMerchantRequest proto.InternalMessageInfo

func (m *UpdateMerchantRequest) GetMerchantuid() string {
	if m != nil {
		return m.Merchantuid
	}
	return ""
}

func (m *UpdateMerchantRequest) GetStoreemail() string {
	if m != nil {
		return m.Storeemail
	}
	return ""
}

func (m *UpdateMerchantRequest) GetStorename() string {
	if m != nil {
		return m.Storename
	}
	return ""
}

func (m *UpdateMerchantRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type VerifyRTAccountRequest struct {
	Recipientuid         string   `protobuf:"bytes,1,opt,name=recipientuid,proto3" json:"recipientuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRTAccountRequest) Reset()         { *m = VerifyRTAccountRequest{} }
func (m *VerifyRTAccountRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRTAccountRequest) ProtoMessage()    {}
func (*VerifyRTAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{3}
}

func (m *VerifyRTAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRTAccountRequest.Unmarshal(m, b)
}
func (m *VerifyRTAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRTAccountRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRTAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRTAccountRequest.Merge(m, src)
}
func (m *VerifyRTAccountRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRTAccountRequest.Size(m)
}
func (m *VerifyRTAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRTAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRTAccountRequest proto.InternalMessageInfo

func (m *VerifyRTAccountRequest) GetRecipientuid() string {
	if m != nil {
		return m.Recipientuid
	}
	return ""
}

type RTAccountBalanceVerified struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Balance              float32  `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RTAccountBalanceVerified) Reset()         { *m = RTAccountBalanceVerified{} }
func (m *RTAccountBalanceVerified) String() string { return proto.CompactTextString(m) }
func (*RTAccountBalanceVerified) ProtoMessage()    {}
func (*RTAccountBalanceVerified) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{4}
}

func (m *RTAccountBalanceVerified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RTAccountBalanceVerified.Unmarshal(m, b)
}
func (m *RTAccountBalanceVerified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RTAccountBalanceVerified.Marshal(b, m, deterministic)
}
func (m *RTAccountBalanceVerified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RTAccountBalanceVerified.Merge(m, src)
}
func (m *RTAccountBalanceVerified) XXX_Size() int {
	return xxx_messageInfo_RTAccountBalanceVerified.Size(m)
}
func (m *RTAccountBalanceVerified) XXX_DiscardUnknown() {
	xxx_messageInfo_RTAccountBalanceVerified.DiscardUnknown(m)
}

var xxx_messageInfo_RTAccountBalanceVerified proto.InternalMessageInfo

func (m *RTAccountBalanceVerified) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *RTAccountBalanceVerified) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*Merchant)(nil), "merchant.Merchant")
	proto.RegisterType((*CreateMerchantRequest)(nil), "merchant.CreateMerchantRequest")
	proto.RegisterType((*UpdateMerchantRequest)(nil), "merchant.UpdateMerchantRequest")
	proto.RegisterType((*VerifyRTAccountRequest)(nil), "merchant.VerifyRTAccountRequest")
	proto.RegisterType((*RTAccountBalanceVerified)(nil), "merchant.RTAccountBalanceVerified")
}

func init() { proto.RegisterFile("rpc/merchant/merchant.proto", fileDescriptor_58ecbaafc626f209) }

var fileDescriptor_58ecbaafc626f209 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x6d, 0xb6, 0xb0, 0xec, 0x4e, 0x0b, 0x95, 0x2c, 0xb5, 0xb2, 0x02, 0xa2, 0x91, 0x4f, 0xbd,
	0x34, 0x41, 0xe5, 0x84, 0x84, 0x84, 0x5a, 0x0e, 0x9c, 0x2a, 0xa1, 0x50, 0x90, 0xe0, 0x52, 0x39,
	0xce, 0x6c, 0x6a, 0x29, 0x5e, 0x07, 0xc7, 0x59, 0xd4, 0xaf, 0xe0, 0x8f, 0x2b, 0x54, 0x6f, 0x9c,
	0x64, 0x57, 0x59, 0x38, 0x72, 0xf3, 0x8c, 0xdf, 0xbc, 0xbc, 0xf7, 0xc6, 0x81, 0x97, 0xa6, 0x12,
	0x89, 0x42, 0x23, 0xee, 0xf8, 0xd2, 0x76, 0x87, 0xb8, 0x32, 0xda, 0x6a, 0x32, 0xf3, 0x75, 0x78,
	0x5a, 0x68, 0x5d, 0x94, 0x98, 0xb8, 0x7e, 0xd6, 0x2c, 0x12, 0x2b, 0x15, 0xd6, 0x96, 0xab, 0x6a,
	0x0d, 0x65, 0x0f, 0x01, 0xcc, 0xae, 0x5b, 0x34, 0x89, 0xe0, 0xc0, 0x4f, 0x36, 0x32, 0xa7, 0x41,
	0x14, 0x9c, 0xcd, 0xd3, 0x61, 0x8b, 0xbc, 0x06, 0xa8, 0xad, 0x36, 0x88, 0x8a, 0xcb, 0x92, 0x4e,
	0x1c, 0x60, 0xd0, 0x21, 0xaf, 0x60, 0xee, 0xaa, 0x25, 0x57, 0x48, 0xf7, 0xdd, 0x75, 0xdf, 0x20,
	0x27, 0x30, 0xfd, 0xc5, 0xcb, 0x12, 0x2d, 0x7d, 0xe2, 0xae, 0xda, 0x8a, 0xbc, 0x03, 0x10, 0x06,
	0xb9, 0xc5, 0xfc, 0x96, 0x5b, 0xfa, 0x34, 0x0a, 0xce, 0x0e, 0x2e, 0xc2, 0x78, 0x2d, 0x3d, 0xf6,
	0xd2, 0xe3, 0x1b, 0x2f, 0x3d, 0x9d, 0xb7, 0xe8, 0x4b, 0x4b, 0x3e, 0xc0, 0xf3, 0x92, 0xd7, 0xf6,
	0x56, 0xe9, 0x5c, 0x2e, 0x24, 0xe6, 0x74, 0xfa, 0xcf, 0xe9, 0xc3, 0xc7, 0x81, 0xeb, 0x16, 0xcf,
	0x14, 0x1c, 0x7f, 0x74, 0x6c, 0x3e, 0x85, 0x14, 0x7f, 0x36, 0x58, 0xdb, 0x2d, 0xab, 0xc1, 0xdf,
	0xad, 0x4e, 0x76, 0x5b, 0xdd, 0x1f, 0x5a, 0x65, 0xbf, 0x03, 0x38, 0xfe, 0x5a, 0xe5, 0x23, 0xdf,
	0xfb, 0x4f, 0xe1, 0xb3, 0xf7, 0x70, 0xf2, 0x0d, 0x8d, 0x5c, 0xdc, 0xa7, 0x37, 0x97, 0x42, 0xe8,
	0xa6, 0x57, 0xc4, 0xe0, 0xd0, 0xa0, 0x90, 0x95, 0xc4, 0xa1, 0xa4, 0x8d, 0x1e, 0xfb, 0x0c, 0xb4,
	0x9b, 0xbb, 0xe2, 0x25, 0x5f, 0x0a, 0x74, 0x6c, 0x12, 0x73, 0x12, 0xc2, 0x6c, 0xd5, 0x9e, 0xdd,
	0xec, 0x2c, 0xed, 0x6a, 0x42, 0xe1, 0x59, 0xb6, 0x86, 0x3b, 0x23, 0x93, 0xd4, 0x97, 0x17, 0x0f,
	0x01, 0x1c, 0xf9, 0x6c, 0xbe, 0xa0, 0x59, 0x49, 0x81, 0xe4, 0x13, 0xbc, 0xd8, 0x5c, 0x12, 0x39,
	0x8d, 0xbb, 0x37, 0x3f, 0xba, 0xbe, 0x90, 0xf4, 0x00, 0x7f, 0xc5, 0xf6, 0x1e, 0x89, 0x36, 0xd3,
	0x1f, 0x12, 0x8d, 0xee, 0x65, 0x07, 0xd1, 0x77, 0x38, 0xda, 0x4a, 0x8d, 0x44, 0x3d, 0x70, 0x3c,
	0xd0, 0x90, 0xf5, 0x88, 0x5d, 0xa1, 0xb1, 0xbd, 0xab, 0x37, 0x3f, 0xe2, 0x42, 0xda, 0xbb, 0x26,
	0x8b, 0x85, 0x56, 0x89, 0x69, 0x54, 0x6d, 0xb8, 0x92, 0x49, 0x21, 0x57, 0xe5, 0xfd, 0xb9, 0xa9,
	0xc4, 0x39, 0xaf, 0x64, 0x32, 0xfc, 0xfd, 0xb3, 0xa9, 0x7b, 0xe5, 0x6f, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xce, 0x55, 0x94, 0x78, 0x15, 0x04, 0x00, 0x00,
}
