// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/merchant/merchant.proto

package merchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Merchant struct {
	Merchantuid          string               `protobuf:"bytes,1,opt,name=merchantuid,proto3" json:"merchantuid,omitempty"`
	Storeemail           string               `protobuf:"bytes,2,opt,name=storeemail,proto3" json:"storeemail,omitempty"`
	Storename            string               `protobuf:"bytes,3,opt,name=storename,proto3" json:"storename,omitempty"`
	Wallet               string               `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{0}
}

func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchant.Unmarshal(m, b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return xxx_messageInfo_Merchant.Size(m)
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetMerchantuid() string {
	if m != nil {
		return m.Merchantuid
	}
	return ""
}

func (m *Merchant) GetStoreemail() string {
	if m != nil {
		return m.Storeemail
	}
	return ""
}

func (m *Merchant) GetStorename() string {
	if m != nil {
		return m.Storename
	}
	return ""
}

func (m *Merchant) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *Merchant) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Merchant) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type CreateMerchantRequest struct {
	Storeemail           string   `protobuf:"bytes,1,opt,name=storeemail,proto3" json:"storeemail,omitempty"`
	Storename            string   `protobuf:"bytes,2,opt,name=storename,proto3" json:"storename,omitempty"`
	Wallet               string   `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMerchantRequest) Reset()         { *m = CreateMerchantRequest{} }
func (m *CreateMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMerchantRequest) ProtoMessage()    {}
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{1}
}

func (m *CreateMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMerchantRequest.Unmarshal(m, b)
}
func (m *CreateMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMerchantRequest.Marshal(b, m, deterministic)
}
func (m *CreateMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMerchantRequest.Merge(m, src)
}
func (m *CreateMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMerchantRequest.Size(m)
}
func (m *CreateMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMerchantRequest proto.InternalMessageInfo

func (m *CreateMerchantRequest) GetStoreemail() string {
	if m != nil {
		return m.Storeemail
	}
	return ""
}

func (m *CreateMerchantRequest) GetStorename() string {
	if m != nil {
		return m.Storename
	}
	return ""
}

func (m *CreateMerchantRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type UpdateMerchantRequest struct {
	Merchantuid          string   `protobuf:"bytes,1,opt,name=merchantuid,proto3" json:"merchantuid,omitempty"`
	Storeemail           string   `protobuf:"bytes,2,opt,name=storeemail,proto3" json:"storeemail,omitempty"`
	Storename            string   `protobuf:"bytes,3,opt,name=storename,proto3" json:"storename,omitempty"`
	Wallet               string   `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMerchantRequest) Reset()         { *m = UpdateMerchantRequest{} }
func (m *UpdateMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMerchantRequest) ProtoMessage()    {}
func (*UpdateMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{2}
}

func (m *UpdateMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMerchantRequest.Unmarshal(m, b)
}
func (m *UpdateMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMerchantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMerchantRequest.Merge(m, src)
}
func (m *UpdateMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMerchantRequest.Size(m)
}
func (m *UpdateMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMerchantRequest proto.InternalMessageInfo

func (m *UpdateMerchantRequest) GetMerchantuid() string {
	if m != nil {
		return m.Merchantuid
	}
	return ""
}

func (m *UpdateMerchantRequest) GetStoreemail() string {
	if m != nil {
		return m.Storeemail
	}
	return ""
}

func (m *UpdateMerchantRequest) GetStorename() string {
	if m != nil {
		return m.Storename
	}
	return ""
}

func (m *UpdateMerchantRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type VerifyBAccountRequest struct {
	Beneficiaryuid       string   `protobuf:"bytes,1,opt,name=beneficiaryuid,proto3" json:"beneficiaryuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyBAccountRequest) Reset()         { *m = VerifyBAccountRequest{} }
func (m *VerifyBAccountRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyBAccountRequest) ProtoMessage()    {}
func (*VerifyBAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{3}
}

func (m *VerifyBAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyBAccountRequest.Unmarshal(m, b)
}
func (m *VerifyBAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyBAccountRequest.Marshal(b, m, deterministic)
}
func (m *VerifyBAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyBAccountRequest.Merge(m, src)
}
func (m *VerifyBAccountRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyBAccountRequest.Size(m)
}
func (m *VerifyBAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyBAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyBAccountRequest proto.InternalMessageInfo

func (m *VerifyBAccountRequest) GetBeneficiaryuid() string {
	if m != nil {
		return m.Beneficiaryuid
	}
	return ""
}

type BAccountBalanceVerified struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Balance              float32  `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BAccountBalanceVerified) Reset()         { *m = BAccountBalanceVerified{} }
func (m *BAccountBalanceVerified) String() string { return proto.CompactTextString(m) }
func (*BAccountBalanceVerified) ProtoMessage()    {}
func (*BAccountBalanceVerified) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ecbaafc626f209, []int{4}
}

func (m *BAccountBalanceVerified) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BAccountBalanceVerified.Unmarshal(m, b)
}
func (m *BAccountBalanceVerified) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BAccountBalanceVerified.Marshal(b, m, deterministic)
}
func (m *BAccountBalanceVerified) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BAccountBalanceVerified.Merge(m, src)
}
func (m *BAccountBalanceVerified) XXX_Size() int {
	return xxx_messageInfo_BAccountBalanceVerified.Size(m)
}
func (m *BAccountBalanceVerified) XXX_DiscardUnknown() {
	xxx_messageInfo_BAccountBalanceVerified.DiscardUnknown(m)
}

var xxx_messageInfo_BAccountBalanceVerified proto.InternalMessageInfo

func (m *BAccountBalanceVerified) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *BAccountBalanceVerified) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*Merchant)(nil), "merchant.Merchant")
	proto.RegisterType((*CreateMerchantRequest)(nil), "merchant.CreateMerchantRequest")
	proto.RegisterType((*UpdateMerchantRequest)(nil), "merchant.UpdateMerchantRequest")
	proto.RegisterType((*VerifyBAccountRequest)(nil), "merchant.VerifyBAccountRequest")
	proto.RegisterType((*BAccountBalanceVerified)(nil), "merchant.BAccountBalanceVerified")
}

func init() { proto.RegisterFile("rpc/merchant/merchant.proto", fileDescriptor_58ecbaafc626f209) }

var fileDescriptor_58ecbaafc626f209 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0x74, 0xa1, 0xa4, 0xb3, 0x50, 0x24, 0x4b, 0x85, 0x28, 0x20, 0xb6, 0xe4, 0x80, 0xf6,
	0xb2, 0x09, 0x5a, 0x4e, 0x9c, 0x56, 0x5b, 0x0e, 0x9c, 0x56, 0x48, 0x01, 0xf6, 0xc0, 0x65, 0xe5,
	0x38, 0x93, 0xd4, 0x52, 0x1c, 0x07, 0xc7, 0x29, 0xea, 0x57, 0xf0, 0xc1, 0x48, 0x08, 0xd5, 0x8d,
	0x9b, 0xb4, 0x4a, 0xe1, 0xc8, 0xcd, 0x33, 0x7e, 0xf3, 0xf2, 0xde, 0x1b, 0x07, 0x5e, 0xa8, 0x8a,
	0x45, 0x02, 0x15, 0x5b, 0xd2, 0x52, 0xef, 0x0e, 0x61, 0xa5, 0xa4, 0x96, 0xc4, 0xb5, 0xb5, 0x7f,
	0x9e, 0x4b, 0x99, 0x17, 0x18, 0x99, 0x7e, 0xd2, 0x64, 0x91, 0xe6, 0x02, 0x6b, 0x4d, 0x45, 0xb5,
	0x85, 0x06, 0xbf, 0x1d, 0x70, 0x6f, 0x5b, 0x34, 0x99, 0xc3, 0x99, 0x9d, 0x6c, 0x78, 0xea, 0x39,
	0x73, 0xe7, 0x62, 0x12, 0xf7, 0x5b, 0xe4, 0x15, 0x40, 0xad, 0xa5, 0x42, 0x14, 0x94, 0x17, 0xde,
	0xc8, 0x00, 0x7a, 0x1d, 0xf2, 0x12, 0x26, 0xa6, 0x2a, 0xa9, 0x40, 0xef, 0xd4, 0x5c, 0x77, 0x0d,
	0xf2, 0x0c, 0xc6, 0x3f, 0x68, 0x51, 0xa0, 0xf6, 0x1e, 0x98, 0xab, 0xb6, 0x22, 0xef, 0x01, 0x98,
	0x42, 0xaa, 0x31, 0xbd, 0xa7, 0xda, 0x7b, 0x38, 0x77, 0x2e, 0xce, 0xae, 0xfc, 0x70, 0x2b, 0x3d,
	0xb4, 0xd2, 0xc3, 0x2f, 0x56, 0x7a, 0x3c, 0x69, 0xd1, 0x37, 0x9a, 0x5c, 0xc3, 0x93, 0x82, 0xd6,
	0xfa, 0x5e, 0xc8, 0x94, 0x67, 0x1c, 0x53, 0x6f, 0xfc, 0xcf, 0xe9, 0xc7, 0x9b, 0x81, 0xdb, 0x16,
	0x1f, 0x08, 0x98, 0x7d, 0x30, 0x6c, 0x36, 0x85, 0x18, 0xbf, 0x37, 0x58, 0xeb, 0x03, 0xab, 0xce,
	0xdf, 0xad, 0x8e, 0x8e, 0x5b, 0x3d, 0xed, 0x5b, 0x0d, 0x7e, 0x3a, 0x30, 0xfb, 0x5a, 0xa5, 0x03,
	0xdf, 0xfb, 0x4f, 0xe1, 0x07, 0xd7, 0x30, 0xbb, 0x43, 0xc5, 0xb3, 0xf5, 0xe2, 0x86, 0x31, 0xd9,
	0x74, 0x82, 0xde, 0xc0, 0x34, 0xc1, 0x12, 0x33, 0xce, 0x38, 0x55, 0xeb, 0x4e, 0xd3, 0x41, 0x37,
	0xf8, 0x04, 0xcf, 0xed, 0xe8, 0x82, 0x16, 0xb4, 0x64, 0x68, 0xf8, 0x38, 0xa6, 0xc4, 0x07, 0x77,
	0xd5, 0x9e, 0xcd, 0xb0, 0x1b, 0xef, 0x6a, 0xe2, 0xc1, 0xa3, 0x64, 0x0b, 0x37, 0x56, 0x46, 0xb1,
	0x2d, 0xaf, 0x7e, 0x39, 0xf0, 0xd4, 0xa6, 0xf3, 0x19, 0xd5, 0x8a, 0x33, 0x24, 0x1f, 0x61, 0xba,
	0xbf, 0x26, 0x72, 0x1e, 0xee, 0x5e, 0xfd, 0xe0, 0x02, 0x7d, 0xd2, 0x01, 0xec, 0x55, 0x70, 0xb2,
	0x21, 0xda, 0xcf, 0xbf, 0x4f, 0x34, 0xb8, 0x99, 0x23, 0x44, 0x77, 0x30, 0xdd, 0xcf, 0xad, 0x4f,
	0x34, 0x98, 0xa8, 0xff, 0xba, 0x03, 0x1c, 0x49, 0x2c, 0x38, 0x59, 0xbc, 0xfd, 0x16, 0xe6, 0x5c,
	0x2f, 0x9b, 0x24, 0x64, 0x52, 0x44, 0xaa, 0x11, 0xb5, 0xa2, 0x82, 0x47, 0x39, 0x5f, 0x15, 0xeb,
	0x4b, 0x55, 0xb1, 0x4b, 0x5a, 0xf1, 0xa8, 0xff, 0xf7, 0x27, 0x63, 0xf3, 0xc8, 0xdf, 0xfd, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x47, 0x8d, 0x9a, 0x84, 0x14, 0x04, 0x00, 0x00,
}
