// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/rpc/merchant/merchant.proto

package merchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Merchant struct {
	// Hash of the email
	MerchantUuid string `protobuf:"bytes,1,opt,name=merchantUuid,proto3" json:"merchantUuid,omitempty"`
	// Created from crypto endpoint
	MerchantCryptoId string `protobuf:"bytes,2,opt,name=merchantCryptoId,proto3" json:"merchantCryptoId,omitempty"`
	// Entered on signup
	StoreEmail string `protobuf:"bytes,3,opt,name=storeEmail,proto3" json:"storeEmail,omitempty"`
	// Entered on signup
	StoreName string `protobuf:"bytes,4,opt,name=storeName,proto3" json:"storeName,omitempty"`
	// Created on Merchant creation
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac56447b6060166a, []int{0}
}

func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchant.Unmarshal(m, b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return xxx_messageInfo_Merchant.Size(m)
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetMerchantUuid() string {
	if m != nil {
		return m.MerchantUuid
	}
	return ""
}

func (m *Merchant) GetMerchantCryptoId() string {
	if m != nil {
		return m.MerchantCryptoId
	}
	return ""
}

func (m *Merchant) GetStoreEmail() string {
	if m != nil {
		return m.StoreEmail
	}
	return ""
}

func (m *Merchant) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *Merchant) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateMerchantReq struct {
	// Entered on signup
	StoreEmail string `protobuf:"bytes,1,opt,name=storeEmail,proto3" json:"storeEmail,omitempty"`
	// Entered on signup
	StoreName            string   `protobuf:"bytes,2,opt,name=storeName,proto3" json:"storeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMerchantReq) Reset()         { *m = CreateMerchantReq{} }
func (m *CreateMerchantReq) String() string { return proto.CompactTextString(m) }
func (*CreateMerchantReq) ProtoMessage()    {}
func (*CreateMerchantReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac56447b6060166a, []int{1}
}

func (m *CreateMerchantReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMerchantReq.Unmarshal(m, b)
}
func (m *CreateMerchantReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMerchantReq.Marshal(b, m, deterministic)
}
func (m *CreateMerchantReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMerchantReq.Merge(m, src)
}
func (m *CreateMerchantReq) XXX_Size() int {
	return xxx_messageInfo_CreateMerchantReq.Size(m)
}
func (m *CreateMerchantReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMerchantReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMerchantReq proto.InternalMessageInfo

func (m *CreateMerchantReq) GetStoreEmail() string {
	if m != nil {
		return m.StoreEmail
	}
	return ""
}

func (m *CreateMerchantReq) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

type RecipientBalanceReq struct {
	// Recieved from crypto endpoint
	RecipientCryptoId    string   `protobuf:"bytes,1,opt,name=recipientCryptoId,proto3" json:"recipientCryptoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipientBalanceReq) Reset()         { *m = RecipientBalanceReq{} }
func (m *RecipientBalanceReq) String() string { return proto.CompactTextString(m) }
func (*RecipientBalanceReq) ProtoMessage()    {}
func (*RecipientBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac56447b6060166a, []int{2}
}

func (m *RecipientBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipientBalanceReq.Unmarshal(m, b)
}
func (m *RecipientBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipientBalanceReq.Marshal(b, m, deterministic)
}
func (m *RecipientBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipientBalanceReq.Merge(m, src)
}
func (m *RecipientBalanceReq) XXX_Size() int {
	return xxx_messageInfo_RecipientBalanceReq.Size(m)
}
func (m *RecipientBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipientBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecipientBalanceReq proto.InternalMessageInfo

func (m *RecipientBalanceReq) GetRecipientCryptoId() string {
	if m != nil {
		return m.RecipientCryptoId
	}
	return ""
}

type RecipientBalance struct {
	// Balance of the recipient
	Balance              float32  `protobuf:"fixed32,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecipientBalance) Reset()         { *m = RecipientBalance{} }
func (m *RecipientBalance) String() string { return proto.CompactTextString(m) }
func (*RecipientBalance) ProtoMessage()    {}
func (*RecipientBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac56447b6060166a, []int{3}
}

func (m *RecipientBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipientBalance.Unmarshal(m, b)
}
func (m *RecipientBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipientBalance.Marshal(b, m, deterministic)
}
func (m *RecipientBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipientBalance.Merge(m, src)
}
func (m *RecipientBalance) XXX_Size() int {
	return xxx_messageInfo_RecipientBalance.Size(m)
}
func (m *RecipientBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipientBalance.DiscardUnknown(m)
}

var xxx_messageInfo_RecipientBalance proto.InternalMessageInfo

func (m *RecipientBalance) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*Merchant)(nil), "merchant.Merchant")
	proto.RegisterType((*CreateMerchantReq)(nil), "merchant.CreateMerchantReq")
	proto.RegisterType((*RecipientBalanceReq)(nil), "merchant.RecipientBalanceReq")
	proto.RegisterType((*RecipientBalance)(nil), "merchant.RecipientBalance")
}

func init() { proto.RegisterFile("pkg/rpc/merchant/merchant.proto", fileDescriptor_ac56447b6060166a) }

var fileDescriptor_ac56447b6060166a = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0x19, 0xfe, 0x83, 0x57, 0xa3, 0x50, 0x2e, 0xcb, 0xfc, 0x03, 0xd9, 0x89, 0x18, 0xd8,
	0x12, 0xf4, 0xe0, 0x55, 0x16, 0x63, 0x3c, 0x68, 0xe2, 0xd4, 0x8b, 0xb7, 0xae, 0xd4, 0xd1, 0xb8,
	0xb2, 0x5a, 0x3a, 0x12, 0xbe, 0x92, 0x1f, 0xc7, 0x4f, 0x64, 0xec, 0x2c, 0x93, 0x4d, 0xbd, 0xf5,
	0x79, 0xde, 0xa7, 0x6f, 0x9e, 0xdf, 0x3a, 0xe8, 0x8a, 0xd7, 0xd8, 0x97, 0x82, 0xf8, 0x9c, 0x4a,
	0x32, 0xc5, 0x33, 0xb5, 0x3a, 0x78, 0x42, 0xa6, 0x2a, 0x45, 0x0d, 0xa3, 0x9d, 0x6e, 0x9c, 0xa6,
	0x71, 0x42, 0x7d, 0xed, 0x47, 0xd9, 0x8b, 0xaf, 0x18, 0xa7, 0x73, 0x85, 0xb9, 0xc8, 0xa3, 0xee,
	0x87, 0x05, 0x8d, 0xdb, 0xef, 0x34, 0x72, 0x61, 0xcf, 0xdc, 0x7c, 0xca, 0xd8, 0xc4, 0xb6, 0x7a,
	0x56, 0xbf, 0x19, 0xae, 0x79, 0xe8, 0x14, 0x5a, 0x46, 0x07, 0x72, 0x29, 0x54, 0x7a, 0x33, 0xb1,
	0xeb, 0x3a, 0x57, 0xf1, 0xd1, 0x09, 0xc0, 0x5c, 0xa5, 0x92, 0x5e, 0x71, 0xcc, 0x12, 0x7b, 0x43,
	0xa7, 0x7e, 0x38, 0xe8, 0x08, 0x9a, 0x5a, 0xdd, 0x61, 0x4e, 0xed, 0x4d, 0x3d, 0x2e, 0x0c, 0x74,
	0x01, 0x4d, 0x22, 0x29, 0x56, 0x74, 0x72, 0xa9, 0xec, 0xad, 0x9e, 0xd5, 0xdf, 0x1d, 0x39, 0x5e,
	0xce, 0xe3, 0x19, 0x1e, 0xef, 0xd1, 0xf0, 0x84, 0x45, 0xd8, 0xbd, 0x87, 0x76, 0xa0, 0x85, 0x21,
	0x0b, 0xe9, 0x5b, 0xa9, 0x8c, 0xf5, 0x7f, 0x99, 0x7a, 0xa9, 0x8c, 0x1b, 0x40, 0x27, 0xa4, 0x84,
	0x09, 0x46, 0x67, 0x6a, 0x8c, 0x13, 0x3c, 0x23, 0xf4, 0x6b, 0xe9, 0x00, 0xda, 0xd2, 0xd8, 0xab,
	0xcf, 0x91, 0xef, 0xae, 0x0e, 0xdc, 0x01, 0xb4, 0xca, 0x4b, 0x90, 0x0d, 0x3b, 0x51, 0x7e, 0xd4,
	0xf7, 0xea, 0xa1, 0x91, 0xa3, 0x77, 0x0b, 0x0e, 0x0c, 0xc0, 0x03, 0x95, 0x0b, 0x46, 0x28, 0x0a,
	0x60, 0x7f, 0x9d, 0x0c, 0x1d, 0x7a, 0xab, 0xc7, 0xaf, 0x30, 0x3b, 0xa8, 0x18, 0x1a, 0xdb, 0xad,
	0xa1, 0x10, 0x3a, 0xd7, 0x54, 0x55, 0x9a, 0x1c, 0x17, 0xe1, 0x5f, 0x50, 0x1d, 0xe7, 0xef, 0xb1,
	0x5b, 0x1b, 0x9f, 0x3f, 0x8f, 0x62, 0xa6, 0xa6, 0x59, 0xe4, 0x91, 0x94, 0xfb, 0x32, 0xe3, 0x73,
	0x89, 0x39, 0xf3, 0x63, 0xb6, 0x48, 0x96, 0x43, 0x29, 0xc8, 0x10, 0x0b, 0xe6, 0x97, 0xff, 0xdb,
	0x68, 0x5b, 0xbf, 0xe3, 0xd9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0xc5, 0xc4, 0x4b, 0xd2,
	0x02, 0x00, 0x00,
}
